### ISSUE TITLE
Access the dataset/model weights

### ISSUE THREAD

**Issue by YouKenChaw** [coding-groot/cactus#1]
I am writing to inquire if it would be possible to access the dataset/model weights you mentioned that would be made publicly available. I have searched on GitHub but could not locate the training resources. Access to these resources will greatly assist in making fair comparisons later.

**Comment by coding-groot** [comment]
Our dataset and model can be accessed via the following link: 
https://huggingface.co/collections/DLI-Lab/cactus-towards-psychological-counseling-conversations-6672312f6f64b0d7be75dd0b
