### ISSUE TITLE
LLaMa server

### ISSUE THREAD

**Issue by engineerkong** [coding-groot/cactus#2]
Hi, 

Thank you for your nice work.
May I ask which LLaMa server you are using? Since I am using ollama to build a server for LLaMa3 model, it occured a lot of errors when I connected my server IP to this work. E. g. the url "<server IP>/models" doesn't exist.

BR

**Comment by coding-groot** [comment]
I appreciate your interest in our project. We have used vLLM to run our server. If you are using Ollama, there might be differences in configuration or API endpoints.

If you have any further questions or need additional assistance, feel free to reach out.
